### ISSUE TITLE
Error on saving page or DataObject with plugin enabled

### ISSUE THREAD

**Issue by lhasselb** [DrMartinGonzo/ss-tinymce-charcount#1]
Hi there,

first thank you for developing such an nice plugin.
There seems to be a minor issue within the Javascript code.
Whenever I try to save a page with a HtmlEditorField I see the following within the console
(using SS 4.3 with Chrome):

Uncaught TypeError: Cannot read property 'innerHtml' of undefined
    at i (bundle.js?m=1540917252:1)
    at tinymce-cms-5c24d9d8a5.js:16 

This points to line 67 within src/bundles/bundle.js
    editor.theme.panel.find('#charcount')[0].innerHtml(text);

I am not 100% sure but it seems the logic can't find the id #charcount ? 

Nevertheless the characters and words are counted :-)

Cheers 
Lars

**Comment by DrMartinGonzo** [comment]
Sorry for being late.
Thank you for your kind words and for noticing the issue! It should be fixed now.
